/****************************************************************************
* Program/file: ApiFpLlme.h
*
* Copyright (C) by RTX A/S, Denmark.
* These computer program listings and specifications, are the property of
* RTX A/S, Denmark and shall not be reproduced or copied or used in
* whole or in part without written permission from RTX A/S, Denmark.
*
* Programmer: Rasmus Foss 
*
* MODULE: ApiFpLlme
* CONTROLLING DOCUMENT: Phoenix_API_FP_Llme.doc   Revision: 61
* DESCRIPTION: Definition of the ApiFpLlme interface.
* This file is generated by Word from the interface document: Phoenix_API_FP_Llme.doc using InterfaceMacro version 68
*
* DO NOT MAKE CHANGES TO THIS FILE DIRECTLY!
* CHANGES SHOULD ONLY BE MADE TO THE INTERFACE DOCUMENT!
*
****************************************************************************/

/*! \file
* Definition of the ApiFpLlme interface.
*/

/****************************************************************************
*                                  PVCS info
*****************************************************************************

$Author:   TMA  $
$Date:   22 Apr 2013 11:06:10  $
$Revision:   1.3  $
$Modtime:   22 Apr 2013 11:05:40  $
$Archive:   J:/sw/Include/Phoenix/Api/FpLlme/vcs/ApiFpLlme.h_v  $
*/

#ifndef APIFPLLME_H
#define APIFPLLME_H

/****************************************************************************
*                               Include files
****************************************************************************/
/*! The following API header files must be included. */
#include <Api/ApiCfg.h> /* API configuration */
/*! The following API header files must be included. */
#include <Phoenix/Api/Types/ApiTypes.h> /* General types used. */

/****************************************************************************
*                               Macros/Defines
****************************************************************************/

/*! This type describes features available in this API. */
#define API_FP_LLME_EXTENDED_TERMINAL_ID_SUPPORT 0x01

/****************************************************************************
*                     Enumerations/Type definitions/Structs
****************************************************************************/

#if (RTX_CORE_VERSION >= 0x0224)
  #include <Standard/Common/RsPushPack1.h>
#else
  #pragma pack(push,1)
#endif

/* Mail primitives:
  API_FP_LLME_GET_RSSI_REQ = 0x47B0,
  API_FP_LLME_GET_RSSI_CFM = 0x47B1,
  API_FP_LLME_GET_PERFORMANCE_TABLE_REQ = 0x47B2,
  API_FP_LLME_GET_PERFORMANCE_TABLE_CFM = 0x47B3,
  API_FP_LLME_FEATURES_REQ = 0x47B4,
  API_FP_LLME_FEATURES_CFM = 0x47B5,
End of mail primitives. */



/*! This type is used to exchange features between the host and the DECT
   module. */
typedef rsuint8 ApiFpLlmeFeatureType;


/*! Mail without parameters. */
typedef struct ApifpllmeEmptySignalType
{
  RosPrimitiveType Primitive; /*!< Mail primitive. */
} ApifpllmeEmptySignalType;

/*! This mail is used by the API to request the signal strength of an
   ongoing call to the MMI. */
typedef struct ApiFpLlmeGetRssiReqType
{
  RosPrimitiveType Primitive;            /*!< API_FP_LLME_GET_RSSI_REQ = 0x47B0 */
  ApiTerminalIdType TerminalId;        /*!< Selects which Pp to receive RSSI from */
} ApiFpLlmeGetRssiReqType;

/*! This mail is used by the API to return signal strength of an ongoing
   call to the MMI. */
typedef struct ApiFpLlmeGetRssiCfmType
{
  RosPrimitiveType Primitive;            /*!< API_FP_LLME_GET_RSSI_CFM = 0x47B1 */
  RsStatusType Status;                  /*!< Indicates whether the command succeeded or
                                           not. Command will only report SUCCESS if
                                           connection is active. */
  ApiTerminalIdType TerminalId;        /*!< Selected Pp */
  rsuint8 Rssi;                         /*!< Received Signal Strength Indication for the
                                           selected Pp. Range 0x00-0x3F. */
} ApiFpLlmeGetRssiCfmType;

/*! This command is used by the MMI to request the API to return the
   protocol performance table with connection statistics for a specific Pp. */
typedef struct ApiFpLlmeGetPerformanceTableReqType
{
  RosPrimitiveType Primitive;            /*!< API_FP_LLME_GET_PERFORMANCE_TABLE_REQ = 0x47B2 */
  ApiTerminalIdType TerminalId;        /*!< Selects which Pp to receive statistics from */
} ApiFpLlmeGetPerformanceTableReqType;

/*! This mail is used by the API to return the performance table to the MMI.
    The info will represent the latest cc connection while ongoing or completed.
    PerformanceTable counters will be reset when setting up a new connection. */
typedef struct ApiFpLlmeGetPerformanceTableCfmType
{
  RosPrimitiveType Primitive;            /*!< API_FP_LLME_GET_PERFORMANCE_TABLE_CFM = 0x47B3 */
  RsStatusType Status;                  /*!< Indicates whether the command succeeded or
                                           not. */
  ApiTerminalIdType TerminalId;        /*!< Receiving info from Pp */
  rsuint32 PerformanceHandovers;        /*!< Number of Handovers in last call */
  rsuint32 PerformanceSyncFailures;     /*!< SyncFailures in last call */
  rsuint32 PerformanceControlFieldErrs; /*!< PerformanceControlFieldErrs in last call
                                            (ACRC) */
  rsuint32 PerformancePayloadErrs;      /*!< PerformancePayloadErrs in call (XCRC) */
  rsuint32 PerformanceSlidingCollisions; /*!< PerformanceSlidingCollisions in last call
                                             (ZCRC) */
  rsuint32 PerformanceLinkErrsQbit;     /*!< PerformanceLinkErrsQbit in last call (QErr) */
} ApiFpLlmeGetPerformanceTableCfmType;

/*! This command is used to enable/disable features in the FpLlme API.
    Enabling/disabling of extended terminal id will also affect all other APIs
   using TerminalId. */
typedef struct ApiFpLlmeFeaturesReqType
{
  RosPrimitiveType Primitive;            /*!< API_FP_LLME_FEATURES_REQ = 0x47B4 */
  ApiFpLlmeFeatureType ApiFpLlmeFeature; /*!< Requested features */
} ApiFpLlmeFeaturesReqType;

/*! This command confirms the new feature settings. */
typedef struct ApiFpLlmeFeaturesCfmType
{
  RosPrimitiveType Primitive;            /*!< API_FP_LLME_FEATURES_CFM = 0x47B5 */
  RsStatusType Status;
  ApiFpLlmeFeatureType ApiFpLlmeFeature; /*!< Supported features */
} ApiFpLlmeFeaturesCfmType;

#if (RTX_CORE_VERSION >= 0x0224)
  #include <Standard/Common/RsPopPack.h>
#else
  #pragma pack(pop)
#endif

#ifdef __cplusplus
extern "C"
{
#endif
/** \cond internal */

/****************************************************************************
*     Function prototypes for mail packaging and sending(MPS) functions
****************************************************************************/

/****************************************************************************
* FUNCTION:      SendApiFpLlmeGetRssiReq
* DESCRIPTION:   MPS function for sending mails with primitive:
*                API_FP_LLME_GET_RSSI_REQ = 0x47B0
****************************************************************************/
void SendApiFpLlmeGetRssiReq ( RosTaskIdType Src,
                               ApiTerminalIdType TerminalId);
                                                             /*!< Selects which Pp to
                                                                receive RSSI from */

/****************************************************************************
* FUNCTION:      SendApiFpLlmeGetPerformanceTableReq
* DESCRIPTION:   MPS function for sending mails with primitive:
*                API_FP_LLME_GET_PERFORMANCE_TABLE_REQ = 0x47B2
****************************************************************************/
void SendApiFpLlmeGetPerformanceTableReq ( RosTaskIdType Src,
                                           ApiTerminalIdType TerminalId);
                                                             /*!< Selects which Pp to
                                                                receive statistics from */

/****************************************************************************
* FUNCTION:      SendApiFpLlmeFeaturesReq
* DESCRIPTION:   MPS function for sending mails with primitive:
*                API_FP_LLME_FEATURES_REQ = 0x47B4
****************************************************************************/
void SendApiFpLlmeFeaturesReq ( RosTaskIdType Src,
                                ApiFpLlmeFeatureType ApiFpLlmeFeature);
                                                             /*!< Requested features */

/** \endcond */
#ifdef __cplusplus
}
#endif
#endif /*APIFPLLME_H */


