/****************************************************************************
* Program/file: ApiFpNoEmission.h
*
* Copyright (C) by RTX TELECOM A/S, Denmark.
* These computer program listings and specifications, are the property of
* RTX TELECOM A/S, Denmark and shall not be reproduced or copied or used in
* whole or in part without written permission from RTX TELECOM A/S, Denmark.
*
*  Programmer: Rasmus Foss 
*
*  MODULE:                 ApiFpNoEmission
*  CONTROLLING DOCUMENT:   Phoenix_API_FP_NoEmission.doc   Revision: 10
*  SYSTEM DEPENDENCIES:
*
*  DESCRIPTION: Definition of the ApiFpNoEmission interface.
*
*               This file is generated by Word from the interface document:
*                  Phoenix_API_FP_NoEmission.doc using InterfaceMacro version 62
*
*               DO NOT MAKE CHANGES TO THIS FILE DIRECTLY!
*               CHANGES SHOULD ONLY BE MADE TO THE INTERFACE DOCUMENT!
*
****************************************************************************/

/*! \file
* Definition of the ApiFpNoEmission interface.
*/

/****************************************************************************
*                                  PVCS info
*****************************************************************************

$Author:   LEH  $
$Date:   05 Sep 2012 08:20:04  $
$Revision:   1.4  $
$Modtime:   05 Sep 2012 08:13:06  $
$Archive:   J:/sw/Include/Phoenix/Api/FpNoEmission/vcs/ApiFpNoEmission.h_v  $
*/

#ifndef APIFPNOEMISSION_H
#define APIFPNOEMISSION_H

/****************************************************************************
*                               Include files
****************************************************************************/
/*! The following API header files must be included. */
#include <Api/ApiCfg.h> /* API configuration */
/*! The following API header files must be included. */
#include <Phoenix/Api/Types/ApiTypes.h> /* General types used. */

/****************************************************************************
*                               Macros/Defines
****************************************************************************/

/****************************************************************************
*                     Enumerations/Type definitions/Structs
****************************************************************************/

#if (RTX_CORE_VERSION >= 0x0224)
  #include <Standard/Common/RsPushPack1.h>
#else
  #pragma pack(push,1)
#endif

/* Global mail primitives:
  API_FP_MAC_NO_EMISSION_MODE_ENABLE_REQ = 0x4600,
  API_FP_MAC_NO_EMISSION_MODE_DISABLE_REQ = 0x4601,
  API_FP_MAC_NO_EMISSION_MODE_STOP_REQ = 0x4602,
  API_FP_MAC_NO_EMISSION_MODE_PENDING_IND = 0x4603,
  API_FP_MAC_NO_EMISSION_MODE_ACTIVE_IND = 0x4604,
  API_FP_MAC_NO_EMISSION_MODE_STOP_IND = 0x4605,
  API_FP_MAC_NO_EMISSION_MODE_SET_PREF_CARRIER_REQ = 0x4606,
The global mail primitives MUST be defined in Global.h! */




/*! Mail without parameters. */
typedef struct ApifpnoemissionEmptySignalType
{
  RosPrimitiveType Primitive; /*!< Mail primitive. */
} ApifpnoemissionEmptySignalType;

/*! This mail is send from the FpApplication to enable No Emission mode. */
typedef ApifpnoemissionEmptySignalType ApiFpMacNoEmissionModeEnableReqType;

/*! This mail is send from the FpApplication to disable No Emission mode. */
typedef ApifpnoemissionEmptySignalType ApiFpMacNoEmissionModeDisableReqType;

/*! This mail is send from the FpApplication to leave No Emission State to
   be able to make calls. */
typedef ApifpnoemissionEmptySignalType ApiFpMacNoEmissionModeStopReqType;

/*! This mail is used to inform the Application when the PP is answering an
   incoming call. */
typedef ApifpnoemissionEmptySignalType ApiFpMacNoEmissionModePendingIndType;

/*! Signals to the Application that the FP protocol has entered No Emission
   State */
typedef ApifpnoemissionEmptySignalType ApiFpMacNoEmissionModeActiveIndType;

/*! Signals to the Application that the FP protocol has left No Emission
   State */
typedef ApifpnoemissionEmptySignalType ApiFpMacNoEmissionModeStopIndType;

/*! This mail is used by the FpApplication to set the preferred carrier to
   use when exiting No emission mode. */
typedef struct ApiFpMacNoEmissionModeSetPrefCarrierReqType
{
  RosPrimitiveType Primitive;            /*!< API_FP_MAC_NO_EMISSION_MODE_SET_PREF_CARRIER_REQ = 0x4606 */
  rsuint8 PrefCarrier;                  /*!< The preferred carrier:
                                             0x00..0x09: Selected carrier 0-9
                                             0xFF: No preferred carrier */
} ApiFpMacNoEmissionModeSetPrefCarrierReqType;

#if (RTX_CORE_VERSION >= 0x0224)
  #include <Standard/Common/RsPopPack.h>
#else
  #pragma pack(pop)
#endif

#ifdef __cplusplus
extern "C"
{
#endif
/** \cond internal */

/****************************************************************************
*     Function prototypes for mail packaging and sending(MPS) functions
****************************************************************************/

/****************************************************************************
* FUNCTION:      SendApiFpMacNoEmissionModeEnableReq
* DESCRIPTION:   MPS function for sending mails with primitive:
*                API_FP_MAC_NO_EMISSION_MODE_ENABLE_REQ = 0x4600
****************************************************************************/
void SendApiFpMacNoEmissionModeEnableReq ( RosTaskIdType Src );


/****************************************************************************
* FUNCTION:      SendApiFpMacNoEmissionModeDisableReq
* DESCRIPTION:   MPS function for sending mails with primitive:
*                API_FP_MAC_NO_EMISSION_MODE_DISABLE_REQ = 0x4601
****************************************************************************/
void SendApiFpMacNoEmissionModeDisableReq ( RosTaskIdType Src );


/****************************************************************************
* FUNCTION:      SendApiFpMacNoEmissionModeStopReq
* DESCRIPTION:   MPS function for sending mails with primitive:
*                API_FP_MAC_NO_EMISSION_MODE_STOP_REQ = 0x4602
****************************************************************************/
void SendApiFpMacNoEmissionModeStopReq ( RosTaskIdType Src );


/****************************************************************************
* FUNCTION:      SendApiFpMacNoEmissionModeSetPrefCarrierReq
* DESCRIPTION:   MPS function for sending mails with primitive:
*                API_FP_MAC_NO_EMISSION_MODE_SET_PREF_CARRIER_REQ = 0x4606
****************************************************************************/
void SendApiFpMacNoEmissionModeSetPrefCarrierReq ( RosTaskIdType Src,
                                                   rsuint8 PrefCarrier);
                                                             /*!< The preferred carrier:
                                                                  0x00..0x09: Selected
                                                                carrier 0-9
                                                                  0xFF: No preferred
                                                                carrier */

/** \endcond */
#ifdef __cplusplus
}
#endif
#endif /*APIFPNOEMISSION_H */


