/****************************************************************************
* Program/file: ApiFpProject.h
*
* Copyright (C) by RTX A/S, Denmark.
* These computer program listings and specifications, are the property of
* RTX A/S, Denmark and shall not be reproduced or copied or used in
* whole or in part without written permission from RTX A/S, Denmark.
*
* Programmer: Rasmus Foss 
*
* MODULE: ApiFpProject
* CONTROLLING DOCUMENT: CVM480PCM_API_FP_PROJECT.doc   Revision: 2
* DESCRIPTION: Definition of the ApiFpProject interface.
* This file is generated by Word from the interface document: CVM480PCM_API_FP_PROJECT.doc using InterfaceMacro version 68
*
* DO NOT MAKE CHANGES TO THIS FILE DIRECTLY!
* CHANGES SHOULD ONLY BE MADE TO THE INTERFACE DOCUMENT!
*
****************************************************************************/

/*! \file
* Definition of the ApiFpProject interface.
*/

/****************************************************************************
*                                  PVCS info
*****************************************************************************

$Author:   TMA  $
$Date:   10 Jun 2013 21:53:18  $
$Revision:   1.5  $
$Modtime:   10 Jun 2013 21:30:20  $
$Archive:   J:/sw/Projects/NatalieV3/FpCvm/Config/ApiProject/vcs/ApiFpProject.h_v  $
*/

#ifndef APIFPPROJECT_H
#define APIFPPROJECT_H

/****************************************************************************
*                               Include files
****************************************************************************/
/*! The following API files must be included. */
#include <Api/ApiCfg.h>
/*! The following API files must be included. */
#include <Phoenix/Api/Types/ApiTypes.h>

/****************************************************************************
*                               Macros/Defines
****************************************************************************/

/****************************************************************************
*                     Enumerations/Type definitions/Structs
****************************************************************************/

#if (RTX_CORE_VERSION >= 0x0224)
  #include <Standard/Common/RsPushPack1.h>
#else
  #pragma pack(push,1)
#endif

/* Mail primitives:
End of mail primitives. */




/*! Mail without parameters. */
typedef struct ApifpprojectEmptySignalType
{
  RosPrimitiveType Primitive; /*!< Mail primitive. */
} ApifpprojectEmptySignalType;

#if (RTX_CORE_VERSION >= 0x0224)
  #include <Standard/Common/RsPopPack.h>
#else
  #pragma pack(pop)
#endif

#ifdef __cplusplus
extern "C"
{
#endif
/** \cond internal */

/****************************************************************************
*     Function prototypes for mail packaging and sending(MPS) functions
****************************************************************************/

/** \endcond */
#ifdef __cplusplus
}
#endif
#endif /*APIFPPROJECT_H */


