/****************************************************************************
* Program/file: ApiProdTest.h
*
* Copyright (C) by RTX TELECOM A/S, Denmark.
* These computer program listings and specifications, are the property of
* RTX TELECOM A/S, Denmark and shall not be reproduced or copied or used in
* whole or in part without written permission from RTX TELECOM A/S, Denmark.
*
*  Programmer: Rasmus Foss 
*
*  MODULE:                 ApiProdTest
*  CONTROLLING DOCUMENT:   Phoenix_API_ProdTest.doc   Revision: 51
*  SYSTEM DEPENDENCIES:
*
*  DESCRIPTION: Definition of the ApiProdTest interface.
*
*               This file is generated by Word from the interface document:
*                  Phoenix_API_ProdTest.doc using InterfaceMacro version 59
*
*               DO NOT MAKE CHANGES TO THIS FILE DIRECTLY!
*               CHANGES SHOULD ONLY BE MADE TO THE INTERFACE DOCUMENT!
*
****************************************************************************/

/*! \file
* Definition of the ApiProdTest interface.
*/

/****************************************************************************
*                                  PVCS info
*****************************************************************************

$Author:   SS  $
$Date:   27 May 2011 11:23:20  $
$Revision:   1.0  $
$Modtime:   26 May 2011 14:56:32  $
$Archive:   J:/sw/Include/Phoenix/Api/ProdTest/vcs/ApiProdTest.h_v  $
*/

#ifndef APIPRODTEST_H
#define APIPRODTEST_H

/****************************************************************************
*                               Include files
****************************************************************************/
/*! The following API files must be included. */
#include <Api/ApiCfg.h>

#include <Phoenix/Api/Types/ApiTypes.h>

/****************************************************************************
*                               Macros/Defines
****************************************************************************/

/****************************************************************************
*                     Enumerations/Type definitions/Structs
****************************************************************************/

#if (RTX_CORE_VERSION >= 0x0224)
  #include <Standard/Common/RsPushPack1.h>
#else
  #pragma pack(push,1)
#endif

/* Global mail primitives:
  API_PROD_TEST_REQ = 0x4FFE,
  API_PROD_TEST_CFM = 0x4FFF,
The global mail primitives MUST be defined in Global.h! */




/*! Mail without parameters. */
typedef struct ApiprodtestEmptySignalType
{
  RosPrimitiveType Primitive; /*!< Mail primitive. */
} ApiprodtestEmptySignalType;

/*! This mail is used by the MCU to send a Production test command to the
   unit */
typedef struct ApiProdTestReqType
{
  RosPrimitiveType Primitive;            /*!< API_PROD_TEST_REQ = 0x4FFE */
  rsuint16 Opcode;                      /*!< Op-code identifying the HW test command. */
  rsuint16 ParameterLength;             /*!< The total length in bytes of the
                                           parameters. */
  rsuint8 Parameters [1];               /*!< Optional parameters. */
} ApiProdTestReqType;

/*! This mail is used to confirm the API_PROD_TEST_REQ command and return
   requested parameters */
typedef struct ApiProdTestCfmType
{
  RosPrimitiveType Primitive;            /*!< API_PROD_TEST_CFM = 0x4FFF */
  rsuint16 Opcode;                      /*!< Op-code identifying the HW test command. */
  rsuint16 ParameterLength;             /*!< The total length in bytes of the
                                           parameters. */
  rsuint8 Parameters [1];               /*!< Optional parameters. */
} ApiProdTestCfmType;

#if (RTX_CORE_VERSION >= 0x0224)
  #include <Standard/Common/RsPopPack.h>
#else
  #pragma pack(pop)
#endif

#ifdef __cplusplus
extern "C"
{
#endif
/** \cond internal */

/****************************************************************************
*     Function prototypes for mail packaging and sending(MPS) functions
****************************************************************************/

/****************************************************************************
* FUNCTION:      SendApiProdTestReq
* DESCRIPTION:   MPS function for sending mails with primitive:
*                API_PROD_TEST_REQ = 0x4FFE
****************************************************************************/
void SendApiProdTestReq ( RosTaskIdType Src,
                          rsuint16 Opcode,                   /*!< Op-code identifying
                                                                the HW test command. */
                          rsuint16 ParameterLength,          /*!< The total length in
                                                                bytes of the parameters. */
                          rsuint8 Parameters [1]);           /*!< Optional parameters. */

/** \endcond */
#ifdef __cplusplus
}
#endif
#endif /*APIPRODTEST_H */


